### ISSUE TITLE
Server thread/ERROR Parsing error loading recipe autooredictconv:auto_converter

### ISSUE THREAD

**Issue by Caaruzo** [MattDahEpic/AutoOreDictConvert1.8#10]
Receiving the following error in log without a crash, just to let u know for fix.

`16:37:31] [Server thread/ERROR] [FML]: Parsing error loading recipe autooredictconv:auto_converter
com.google.gson.JsonSyntaxException: Unknown item 'autooredictconv:auto_converter'
	at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:213) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:522) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:415) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:676) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_222]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:626) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

#### Affected Versions

- AutoOreDictConvert: **autooredictconv-1.12-1.0.1**
- Minecraft: **1.12.2**
- Forge: **forge-1.12.2-14.23.5.2838-universal**
- SpongeForge? **no**
- Optifine? **no**
- Single Player and/or Server? **Server**

**Comment by Caeas** [comment]
I can reproduce that. Same for me here.

#### Affected Versions

- **AutoOreDictConvert: **autooredictconv-1.12-1.0.1**
- Minecraft: **1.12.2**
- Forge: **forge-1.12.2-14.23.5.2838-universal**
- SpongeForge? **no**
- Optifine? **no**
- Single Player and/or Server? **Server**

#### Most recent log file where the issue was present: 

[latest.log](https://drive.google.com/open?id=1AHVMq_azuKo1mRAEhjGvi-SupnuiVG1m)
[debug.log](https://drive.google.com/open?id=1GJ-V8QsWDv2Cg-qkmhVHOtM-aaANZEVy)
[hs_err_pid6920.log](https://drive.google.com/open?id=175LMIazvbVBp1gFn30lwidCZ9CcbWtcu)

**Comment by DDX5-DX12-Media** [comment]
Just A Note, As A Modder Myself do you have the autocrafter enabled in configs
